---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kite-controller-manager
  namespace: kite-system
  labels:
    app.kubernetes.io/name: kite
    app.kubernetes.io/component: controller-manager
