//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ContainerMetrics) DeepCopyInto(out *ContainerMetrics) {
	*out = *in
}

// DeepCopy generates a deep copy of *ContainerMetrics.
func (in *ContainerMetrics) DeepCopy() *ContainerMetrics {
	if in == nil {
		return nil
	}
	out := new(ContainerMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ContainerRecommendation) DeepCopyInto(out *ContainerRecommendation) {
	*out = *in
}

// DeepCopy generates a deep copy of *ContainerRecommendation.
func (in *ContainerRecommendation) DeepCopy() *ContainerRecommendation {
	if in == nil {
		return nil
	}
	out := new(ContainerRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *GitOpsConfig) DeepCopyInto(out *GitOpsConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.PRLabels != nil {
		in, out := &in.PRLabels, &out.PRLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Reviewers != nil {
		in, out := &in.Reviewers, &out.Reviewers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy generates a deep copy of *GitOpsConfig.
func (in *GitOpsConfig) DeepCopy() *GitOpsConfig {
	if in == nil {
		return nil
	}
	out := new(GitOpsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *MetricsDataPoint) DeepCopyInto(out *MetricsDataPoint) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerMetrics, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy generates a deep copy of *MetricsDataPoint.
func (in *MetricsDataPoint) DeepCopy() *MetricsDataPoint {
	if in == nil {
		return nil
	}
	out := new(MetricsDataPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *MetricsHistory) DeepCopyInto(out *MetricsHistory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy generates a deep copy of *MetricsHistory.
func (in *MetricsHistory) DeepCopy() *MetricsHistory {
	if in == nil {
		return nil
	}
	out := new(MetricsHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *MetricsHistory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *MetricsHistoryList) DeepCopyInto(out *MetricsHistoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MetricsHistory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy generates a deep copy of *MetricsHistoryList.
func (in *MetricsHistoryList) DeepCopy() *MetricsHistoryList {
	if in == nil {
		return nil
	}
	out := new(MetricsHistoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *MetricsHistoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *MetricsHistorySpec) DeepCopyInto(out *MetricsHistorySpec) {
	*out = *in
	out.WorkloadRef = in.WorkloadRef
	if in.DataPoints != nil {
		in, out := &in.DataPoints, &out.DataPoints
		*out = make([]MetricsDataPoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy generates a deep copy of *MetricsHistorySpec.
func (in *MetricsHistorySpec) DeepCopy() *MetricsHistorySpec {
	if in == nil {
		return nil
	}
	out := new(MetricsHistorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *MetricsHistoryStatus) DeepCopyInto(out *MetricsHistoryStatus) {
	*out = *in
}

// DeepCopy generates a deep copy of *MetricsHistoryStatus.
func (in *MetricsHistoryStatus) DeepCopy() *MetricsHistoryStatus {
	if in == nil {
		return nil
	}
	out := new(MetricsHistoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OptimizationTarget) DeepCopyInto(out *OptimizationTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy generates a deep copy of *OptimizationTarget.
func (in *OptimizationTarget) DeepCopy() *OptimizationTarget {
	if in == nil {
		return nil
	}
	out := new(OptimizationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *OptimizationTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OptimizationTargetList) DeepCopyInto(out *OptimizationTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OptimizationTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy generates a deep copy of *OptimizationTargetList.
func (in *OptimizationTargetList) DeepCopy() *OptimizationTargetList {
	if in == nil {
		return nil
	}
	out := new(OptimizationTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *OptimizationTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OptimizationTargetSpec) DeepCopyInto(out *OptimizationTargetSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.ScrapeInterval != nil {
		in, out := &in.ScrapeInterval, &out.ScrapeInterval
		*out = new(v1.Duration)
		**out = **in
	}
	in.Rules.DeepCopyInto(&out.Rules)
	if in.GitOps != nil {
		in, out := &in.GitOps, &out.GitOps
		*out = new(GitOpsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy generates a deep copy of *OptimizationTargetSpec.
func (in *OptimizationTargetSpec) DeepCopy() *OptimizationTargetSpec {
	if in == nil {
		return nil
	}
	out := new(OptimizationTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OptimizationTargetStatus) DeepCopyInto(out *OptimizationTargetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAnalysisTime != nil {
		in, out := &in.LastAnalysisTime, &out.LastAnalysisTime
		*out = new(v1.Time)
		**out = **in
	}
	if in.NextAnalysisTime != nil {
		in, out := &in.NextAnalysisTime, &out.NextAnalysisTime
		*out = new(v1.Time)
		**out = **in
	}
	if in.LastScrapeTime != nil {
		in, out := &in.LastScrapeTime, &out.LastScrapeTime
		*out = new(v1.Time)
		**out = **in
	}
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = make([]WorkloadRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy generates a deep copy of *OptimizationTargetStatus.
func (in *OptimizationTargetStatus) DeepCopy() *OptimizationTargetStatus {
	if in == nil {
		return nil
	}
	out := new(OptimizationTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *RightsizingRules) DeepCopyInto(out *RightsizingRules) {
	*out = *in
	out.MinCPURequest = in.MinCPURequest.DeepCopy()
	out.MinMemoryRequest = in.MinMemoryRequest.DeepCopy()
	if in.CPULimitRatio != nil {
		in, out := &in.CPULimitRatio, &out.CPULimitRatio
		*out = new(string)
		**out = **in
	}
	if in.MemoryLimitRatio != nil {
		in, out := &in.MemoryLimitRatio, &out.MemoryLimitRatio
		*out = new(string)
		**out = **in
	}
	if in.HistoryWindow != nil {
		in, out := &in.HistoryWindow, &out.HistoryWindow
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy generates a deep copy of *RightsizingRules.
func (in *RightsizingRules) DeepCopy() *RightsizingRules {
	if in == nil {
		return nil
	}
	out := new(RightsizingRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *TargetSelector) DeepCopyInto(out *TargetSelector) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy generates a deep copy of *TargetSelector.
func (in *TargetSelector) DeepCopy() *TargetSelector {
	if in == nil {
		return nil
	}
	out := new(TargetSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *WorkloadRecommendation) DeepCopyInto(out *WorkloadRecommendation) {
	*out = *in
	if in.HPAMinReplicas != nil {
		in, out := &in.HPAMinReplicas, &out.HPAMinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.HPAMaxReplicas != nil {
		in, out := &in.HPAMaxReplicas, &out.HPAMaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerRecommendation, len(*in))
		copy(*out, *in)
	}
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
}

// DeepCopy generates a deep copy of *WorkloadRecommendation.
func (in *WorkloadRecommendation) DeepCopy() *WorkloadRecommendation {
	if in == nil {
		return nil
	}
	out := new(WorkloadRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy generates a deep copy of *WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
