// Package gitops provides the GitOps integration layer: it clones a target
// repository, patches the resource requests/limits in the relevant manifest
// file, commits the change on a new branch, and opens a pull request via the
// hosting provider's API.
//
// Supported providers: GitHub, GitLab.
package gitops

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"text/template"
	"time"

	"k8s.io/apimachinery/pkg/api/resource"
	"sigs.k8s.io/yaml"

	"github.com/graz-dev/kite/internal/algorithm"
)

// Provider abstracts over the different Git hosting APIs.
type Provider interface {
	// CreatePR pushes branchName to the remote and opens a pull request.
	CreatePR(ctx context.Context, req PRRequest) (*PRResult, error)
}

// PRRequest contains everything needed to create a pull request.
type PRRequest struct {
	RepoURL    string
	Token      string
	BaseBranch string
	BranchName string
	Title      string
	Body       string
	Labels     []string
	Reviewers  []string
	AutoMerge  bool
	Files      []FileChange
	CommitMsg  string
}

// FileChange describes a single file modification in the commit.
type FileChange struct {
	Path    string
	Content []byte
}

// PRResult is the response from a successful pull-request creation.
type PRResult struct {
	URL    string
	Number int
	Title  string
}

// TemplateVars is passed to Go text/template expressions for PR titles, body,
// commit messages and file path templates.
type TemplateVars struct {
	Namespace       string
	Name            string
	Kind            string
	Recommendations []algorithm.ContainerRec
}

// BranchName generates a deterministic branch name for a workload optimization.
func BranchName(namespace, name, kind string) string {
	ts := time.Now().UTC().Format("20060102-150405")
	raw := fmt.Sprintf("kite/optimize/%s-%s-%s-%s",
		strings.ToLower(kind), namespace, name, ts)
	// Sanitize to only use characters valid in a git ref.
	var b strings.Builder
	for _, r := range raw {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(r >= '0' && r <= '9') || r == '-' || r == '/' || r == '_' || r == '.' {
			b.WriteRune(r)
		} else {
			b.WriteRune('-')
		}
	}
	return b.String()
}

// RenderTemplate renders a Go text/template with TemplateVars.
func RenderTemplate(tmpl string, vars TemplateVars) (string, error) {
	if tmpl == "" {
		return "", nil
	}
	t, err := template.New("").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, vars); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}
	return buf.String(), nil
}

// DefaultPRTitle returns the default PR title when no template is configured.
func DefaultPRTitle(vars TemplateVars) string {
	return fmt.Sprintf("chore(kite): rightsize %s %s/%s", vars.Kind, vars.Namespace, vars.Name)
}

// DefaultPRBody builds a Markdown PR body summarising the recommendations.
func DefaultPRBody(vars TemplateVars) string {
	var sb strings.Builder
	sb.WriteString("## Kite Resource Rightsizing\n\n")
	fmt.Fprintf(&sb, "Automated recommendation for **%s** `%s/%s`.\n\n", vars.Kind, vars.Namespace, vars.Name)
	sb.WriteString("| Container | CPU Request | Memory Request | CPU Diff | Mem Diff |\n")
	sb.WriteString("|-----------|------------|----------------|----------|----------|\n")
	for _, c := range vars.Recommendations {
		fmt.Fprintf(&sb, "| `%s` | %s | %s | %+.1f%% | %+.1f%% |\n",
			c.Name,
			c.RecommendedCPURequest.String(),
			c.RecommendedMemoryRequest.String(),
			c.CPURequestDiffPercent,
			c.MemoryRequestDiffPercent,
		)
	}
	sb.WriteString("\n---\n*Generated by [Kite](https://github.com/graz-dev/kite)*\n")
	return sb.String()
}

// DefaultCommitMessage returns the default commit message.
func DefaultCommitMessage(vars TemplateVars) string {
	return fmt.Sprintf("fix(resources): rightsize %s %s/%s via Kite", vars.Kind, vars.Namespace, vars.Name)
}

// UpdateResourcesInManifest parses a Kubernetes manifest YAML, updates the
// resource requests and limits for the matching containers, and returns the
// patched YAML.
//
// The function handles Deployment, StatefulSet, and DaemonSet manifests.
// Comments and non-resource fields are preserved as faithfully as the
// round-trip through JSON allows.
func UpdateResourcesInManifest(content []byte, recs []algorithm.ContainerRec) ([]byte, error) {
	// Decode to a generic map so we can handle any workload kind.
	var obj map[string]interface{}
	if err := yaml.Unmarshal(content, &obj); err != nil {
		return nil, fmt.Errorf("parsing manifest YAML: %w", err)
	}

	containersPath, err := findContainersPath(obj)
	if err != nil {
		return nil, err
	}

	containers, ok := containersPath.([]interface{})
	if !ok {
		return nil, fmt.Errorf("containers field is not a list")
	}

	// Build a lookup map for quick access.
	recMap := make(map[string]algorithm.ContainerRec, len(recs))
	for _, r := range recs {
		recMap[r.Name] = r
	}

	for i, rawC := range containers {
		cMap, ok := rawC.(map[string]interface{})
		if !ok {
			continue
		}
		name, _ := cMap["name"].(string)
		rec, found := recMap[name]
		if !found {
			continue
		}

		resources := map[string]interface{}{
			"requests": map[string]interface{}{
				"cpu":    rec.RecommendedCPURequest.String(),
				"memory": rec.RecommendedMemoryRequest.String(),
			},
		}
		if rec.RecommendedCPULimit != nil || rec.RecommendedMemoryLimit != nil {
			limits := map[string]interface{}{}
			if rec.RecommendedCPULimit != nil {
				limits["cpu"] = rec.RecommendedCPULimit.String()
			}
			if rec.RecommendedMemoryLimit != nil {
				limits["memory"] = rec.RecommendedMemoryLimit.String()
			}
			resources["limits"] = limits
		}
		cMap["resources"] = resources
		containers[i] = cMap
	}

	// Write containers back into the path.
	if err := setContainersPath(obj, containers); err != nil {
		return nil, err
	}

	// Round-trip through JSON to produce clean YAML.
	jsonBytes, err := json.Marshal(obj)
	if err != nil {
		return nil, fmt.Errorf("marshalling to JSON: %w", err)
	}
	out, err := yaml.JSONToYAML(jsonBytes)
	if err != nil {
		return nil, fmt.Errorf("converting to YAML: %w", err)
	}
	return out, nil
}

// findContainersPath navigates the generic object map and returns a reference
// to the containers list.
func findContainersPath(obj map[string]interface{}) (interface{}, error) {
	// Standard path for Deployment, StatefulSet, DaemonSet, Job, CronJob…
	paths := [][]string{
		{"spec", "template", "spec", "containers"},
		{"spec", "jobTemplate", "spec", "template", "spec", "containers"},
	}
	for _, path := range paths {
		if v, ok := nestedField(obj, path...); ok {
			return v, nil
		}
	}
	return nil, fmt.Errorf("cannot find containers field in manifest (supported kinds: Deployment, StatefulSet, DaemonSet)")
}

func setContainersPath(obj map[string]interface{}, containers []interface{}) error {
	paths := [][]string{
		{"spec", "template", "spec", "containers"},
		{"spec", "jobTemplate", "spec", "template", "spec", "containers"},
	}
	for _, path := range paths {
		if _, ok := nestedField(obj, path...); ok {
			return setNestedField(obj, containers, path...)
		}
	}
	return fmt.Errorf("cannot set containers field")
}

func nestedField(obj map[string]interface{}, fields ...string) (interface{}, bool) {
	var current interface{} = obj
	for _, f := range fields {
		m, ok := current.(map[string]interface{})
		if !ok {
			return nil, false
		}
		current, ok = m[f]
		if !ok {
			return nil, false
		}
	}
	return current, true
}

func setNestedField(obj map[string]interface{}, value interface{}, fields ...string) error {
	m := obj
	for _, f := range fields[:len(fields)-1] {
		next, ok := m[f]
		if !ok {
			return fmt.Errorf("field %q not found", f)
		}
		m, ok = next.(map[string]interface{})
		if !ok {
			return fmt.Errorf("field %q is not a map", f)
		}
	}
	m[fields[len(fields)-1]] = value
	return nil
}

// QuantityToString converts a resource.Quantity pointer to a string, returning
// "" for nil.
func QuantityToString(q *resource.Quantity) string {
	if q == nil {
		return ""
	}
	return q.String()
}
